name: MincraMagicRod
main: mincra.magicrod.main.Magic
version: 1.1
website: http://mincra.ikaduchi.com/plugins.html
author: amutas
depend: [BossBarAPI,ProtocolLib]
commands:
     mincramagicrod:
      description: This is a demo command.
      usage: /mmr <parameta>
      aliases: [magicrod,mmr]
     skill:
      description: This is a demo command.
      usage: /skill
      aliases: [sk]
     giftbox:
      description: This is a demo command.
      usage: /giftbox
     magicchest:
      description: This is a demo command.
      usage: /magicchest /magic /mc
      aliases: [magic,mc]